version: "3.8"

services:
  # Zookeeper for future proofing adding another master, election system
  zookeeper:
    image: zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - sparknet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  spark-master:
    image: apache/spark:3.5.6
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper:2181 -Dspark.deploy.zookeeper.dir=/spark-ha
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - sparknet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1

  spark-worker:
    image: apache/spark:3.5.6
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - PYSPARK_PYTHON=python3
      - PYSPARK_DRIVER_PYTHON=python3
    networks:
      - sparknet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  backend:
    image: distributed-backend:latest
    environment:
      - API_URL=${API_URL:-http://finnhub-client:8001/quote}
      - INFLUXDB_URL=${INFLUXDB_URL:-http://influxdb:8086}
      - INFLUXDB_TOKEN=${INFLUXDB_ADMIN_TOKEN:-local-token}
      - INFLUXDB_ORG=${INFLUXDB_ORG:-trading}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET:-market_data}
    ports:
      - "4000:4000"
    networks:
      - sparknet
      - stock_api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: distributed-frontend:latest
    ports:
      - "8800:8800"
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:4000}
    networks:
      - stock_api
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  finnhub-client:
    image: distributed-finnhub:latest
    ports:
      - "8001:8001"
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - STOCK_SYMBOL=${STOCK_SYMBOL:-NVDA}
    networks:
      - stock_api
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  influxdb:
    image: influxdb:2.7
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD:-password}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-trading}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-market_data}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-local-token}
    ports:
      - "8086:8086"
    networks:
      - stock_api
    volumes:
      - influxdb_data:/var/lib/influxdb2
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  sparknet:
    driver: overlay
    attachable: true
  stock_api:
    driver: overlay
    attachable: true

volumes:
  influxdb_data: