version: "3.8"

services:
  # Zookeeper for future proofing adding another master, election system
  zookeeper:
    image: zookeeper:3.9
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - sparknet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  spark-master:
    image: apache/spark:3.5.6
    command: ["/opt/spark/sbin/start-master.sh"]
    environment:
      - SPARK_NO_DAEMONIZE=true
      - SPARK_DAEMON_JAVA_OPTS=-Dspark.deploy.recoveryMode=ZOOKEEPER -Dspark.deploy.zookeeper.url=zookeeper:2181 -Dspark.deploy.zookeeper.dir=/spark-ha
    ports:
      - "7077:7077"
      - "8080:8080"
    networks:
      - sparknet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        max_replicas_per_node: 1

  spark-worker:
    image: apache/spark:3.5.6
    command: ["/opt/spark/sbin/start-worker.sh", "spark://spark-master:7077"]
    environment:
      - SPARK_NO_DAEMONIZE=true
    networks:
      - sparknet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  backend:
    image: distributed-backend:latest
    ports:
      - "4000:4000"
    networks:
      - sparknet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  frontend:
    image: distributed-frontend:latest
    ports:
      - "8800:8800"
    environment:
      - BACKEND_URL=${BACKEND_URL:-}
    networks:
      - sparknet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure

  finnhub-client:
    image: distributed-finnhub:latest
    ports:
      - "8001:8001"
    environment:
      - FINNHUB_API_KEY=${FINNHUB_API_KEY}
      - STOCK_SYMBOL=${STOCK_SYMBOL:-NVDA}
    networks:
      - sparknet
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  sparknet:
    driver: overlay
    attachable: true